[package]
name = "quizgen"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.98"
rand = "0.9.0"
reqwest = { version = "0.12.15", features = ["blocking", "json"] }
serde = "1.0.219"
url = "2.5.4"
